CREATE DATABASE XYZ_COLLEGE;
USE XYZ_COLLEGE;

CREATE TABLE STUDENT(
 ROLL_NO INT PRIMARY KEY,
 NAME VARCHAR(50),
 MARKS INT NOT NULL,
 GRADE VARCHAR(1),
 CITY VARCHAR(20)
 );

INSERT INTO STUDENT 
(ROLL_NO,NAME,MARKS,GRADE,CITY)
VALUES
 (101,'ANIL',78,'A','PUNE'),
 (102,'BHUMIKA',85,'B','MUMBAI'),
 (103,'CHETAN',79,'C','PUNE'),
 (104,'DHRUV',94,'A','DELHI'),
 (105,'FARAH',95,'B','DELHI');

SELECT *FROM STUDENT;

SELECT NAME,MARKS FROM STUDENT;

SELECT DISTINCT CITY FROM STUDENT;     -------> SAME CITY NOT SHOWING

 --------> USE OF WHERE CLAUSE
SELECT*FROM STUDENT WHERE MARKS>80;
SELECT*FROM STUDENT WHERE CITY='MUMBAI';

 --------> USE OF AND OPERATOR
SELECT*FROM STUDENT WHERE MARKS>80 AND CITY='MUMBAI';

  -------> USE OF OR OPERATOR
SELECT*FROM STUDENT WHERE MARKS>90 OR CITY='MUMBAI';

--------->BETWEEN OPERATOR(SELECT FOR A GIVEN RANGE)
SELECT*FROM STUDENT WHERE MARKS BETWEEN 80 AND 90;  
  
---------> IN OPERATOR(MATCHES THE VALUE)
 SELECT*FROM STUDENT WHERE CITY IN('DELHI','MUMBAI');

 -------> LIMIT CLAUSE
  SELECT*FROM STUDENT LIMIT (3);
   
-------> ORDER BY CLAUSE 
 SELECT*FROM STUDENT ORDER BY MARKS;
 SELECT*FROM STUDENT ORDER BY MARKS DESC;

 ------->Aggregate functions  COUNT(),MAX(),MIN(),SUM(),AVG()
  SELECT AVG(MARKS) FROM STUDENT;

  ------->GROUP BY CLAUSE
  SELECT CITY,COUNT(ROLL_NO) FROM STUDENT GROUP BY CITY;
  SELECT CITY,AVG(MARKS) FROM STUDENT GROUP BY CITY;
  SELECT GRADE,COUNT(ROLL_NO) FROM STUDENT GROUP BY GRADE ORDER BY GRADE;


