CREATE DATABASE COLLEGE;
USE COLLEGE;
CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(100),
AGE INT NOT NULL
);

-------> INSERT DATA IN TABLE

INSERT INTO STUDENT VALUES(1,'APURV',22);
INSERT INTO STUDENT VALUES(2,'VIKAS',24);


-------> TO SHOW TABLE

SELECT *FROM STUDENT;

INSERT INTO STUDENT VALUES (101,'APURVA',22);
INSERT INTO STUDENT VALUES (102,'VIKAS',25);
INSERT INTO STUDENT VALUES (103,'PADOL',26);