---------> CREATE DATABASE FOR COMPANY AND INSERT VALUE 
CREATE DATABASE XYZ_COMPANY;
USE XYZ_COMPANY;

--------> CREATE TABLE 
CREATE TABLE EMPLOYEE (
ID INT PRIMARY KEY,
NAME VARCHAR(50),
SALARY INT 
); 
 
 ---------> INSERT VALUE IN TABLE
INSERT INTO Employee VALUES (1,'ADAM',25000);
INSERT INTO Employee VALUES (2,'BOB',30000);
INSERT INTO Employee VALUES (3,'CASEY',350000);
INSERT INTO Employee VALUES (4,'PICKY',40000);


SELECT *FROM Employee;
